apiVersion: v1
kind: Secret
metadata:
  name: apps-of-apps
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  project: default
  name: apps-of-apps
  url: https://github.com/vagnerfls/apps-of-apps.git