apiVersion: v1
kind: Secret
metadata:
  name: template-app-gitops
  namespace: cicd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/vagnerfls/helm-kustomize.git