apiVersion: v1
kind: Secret
metadata:
  name: ex2
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/vagnerfls/helm-kustomize.git