apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: placeholder
  namespace: argocd 

spec:
  destination:
    namespace: placeholder
    server: https://kubernetes.default.svc

  project: ex3


  source:
    path: .
    repoURL: https://github.com/vagnerfls/helm-kustomize.git
    targetRevision: HEAD

  ignoreDifferences:
    - group: "apps"
      kind: "Deployment"
      jsonPointers:
        - /spec/template/spec/containers/0/image

syncPolicy:
    automated: 
      prune: true 
      selfHeal: true
